/*
 * Copyright (C) 2025 LooKeR & Contributors
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.looker.kenko.ui.theme.colorSchemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import com.looker.kenko.R

// Blue & Pink

private val primaryLight = Color(0xFF0005B8)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFF2631FC)
private val onPrimaryContainerLight = Color(0xFFFFFDFF)
private val secondaryLight = Color(0xFF4E55B0)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFA4AAFF)
private val onSecondaryContainerLight = Color(0xFF0F1475)
private val tertiaryLight = Color(0xFF5D0071)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFF8E20A7)
private val onTertiaryContainerLight = Color(0xFFFFFCFF)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF410002)
private val backgroundLight = Color(0xFFFBF8FF)
private val onBackgroundLight = Color(0xFF1A1B25)
private val surfaceLight = Color(0xFFFBF8FF)
private val onSurfaceLight = Color(0xFF1A1B25)
private val surfaceVariantLight = Color(0xFFE2E0F7)
private val onSurfaceVariantLight = Color(0xFF454557)
private val outlineLight = Color(0xFF757589)
private val outlineVariantLight = Color(0xFFC5C4DA)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF2F2F3B)
private val inverseOnSurfaceLight = Color(0xFFF1EFFE)
private val inversePrimaryLight = Color(0xFFBEC2FF)
private val surfaceDimLight = Color(0xFFDAD8E7)
private val surfaceBrightLight = Color(0xFFFBF8FF)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFF4F2FF)
private val surfaceContainerLight = Color(0xFFEEECFB)
private val surfaceContainerHighLight = Color(0xFFE9E6F6)
private val surfaceContainerHighestLight = Color(0xFFE3E1F0)

private val primaryLightMediumContrast = Color(0xFF0005B8)
private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
private val primaryContainerLightMediumContrast = Color(0xFF2631FC)
private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryLightMediumContrast = Color(0xFF313892)
private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightMediumContrast = Color(0xFF656CC8)
private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryLightMediumContrast = Color(0xFF5D0071)
private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightMediumContrast = Color(0xFF8E20A7)
private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val errorLightMediumContrast = Color(0xFF8C0009)
private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
private val errorContainerLightMediumContrast = Color(0xFFDA342E)
private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
private val backgroundLightMediumContrast = Color(0xFFFBF8FF)
private val onBackgroundLightMediumContrast = Color(0xFF1A1B25)
private val surfaceLightMediumContrast = Color(0xFFFBF8FF)
private val onSurfaceLightMediumContrast = Color(0xFF1A1B25)
private val surfaceVariantLightMediumContrast = Color(0xFFE2E0F7)
private val onSurfaceVariantLightMediumContrast = Color(0xFF414153)
private val outlineLightMediumContrast = Color(0xFF5D5E70)
private val outlineVariantLightMediumContrast = Color(0xFF79798C)
private val scrimLightMediumContrast = Color(0xFF000000)
private val inverseSurfaceLightMediumContrast = Color(0xFF2F2F3B)
private val inverseOnSurfaceLightMediumContrast = Color(0xFFF1EFFE)
private val inversePrimaryLightMediumContrast = Color(0xFFBEC2FF)
private val surfaceDimLightMediumContrast = Color(0xFFDAD8E7)
private val surfaceBrightLightMediumContrast = Color(0xFFFBF8FF)
private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightMediumContrast = Color(0xFFF4F2FF)
private val surfaceContainerLightMediumContrast = Color(0xFFEEECFB)
private val surfaceContainerHighLightMediumContrast = Color(0xFFE9E6F6)
private val surfaceContainerHighestLightMediumContrast = Color(0xFFE3E1F0)

private val primaryLightHighContrast = Color(0xFF000380)
private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
private val primaryContainerLightHighContrast = Color(0xFF0008E0)
private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val secondaryLightHighContrast = Color(0xFF090F72)
private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightHighContrast = Color(0xFF313892)
private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryLightHighContrast = Color(0xFF3F004E)
private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightHighContrast = Color(0xFF73008C)
private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val errorLightHighContrast = Color(0xFF4E0002)
private val onErrorLightHighContrast = Color(0xFFFFFFFF)
private val errorContainerLightHighContrast = Color(0xFF8C0009)
private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
private val backgroundLightHighContrast = Color(0xFFFBF8FF)
private val onBackgroundLightHighContrast = Color(0xFF1A1B25)
private val surfaceLightHighContrast = Color(0xFFFBF8FF)
private val onSurfaceLightHighContrast = Color(0xFF000000)
private val surfaceVariantLightHighContrast = Color(0xFFE2E0F7)
private val onSurfaceVariantLightHighContrast = Color(0xFF222333)
private val outlineLightHighContrast = Color(0xFF414153)
private val outlineVariantLightHighContrast = Color(0xFF414153)
private val scrimLightHighContrast = Color(0xFF000000)
private val inverseSurfaceLightHighContrast = Color(0xFF2F2F3B)
private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
private val inversePrimaryLightHighContrast = Color(0xFFEBEAFF)
private val surfaceDimLightHighContrast = Color(0xFFDAD8E7)
private val surfaceBrightLightHighContrast = Color(0xFFFBF8FF)
private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightHighContrast = Color(0xFFF4F2FF)
private val surfaceContainerLightHighContrast = Color(0xFFEEECFB)
private val surfaceContainerHighLightHighContrast = Color(0xFFE9E6F6)
private val surfaceContainerHighestLightHighContrast = Color(0xFFE3E1F0)

private val primaryDark = Color(0xFFBEC2FF)
private val onPrimaryDark = Color(0xFF0004AA)
private val primaryContainerDark = Color(0xFF0007D8)
private val onPrimaryContainerDark = Color(0xFFD0D2FF)
private val secondaryDark = Color(0xFFBEC2FF)
private val onSecondaryDark = Color(0xFF1D237F)
private val secondaryContainerDark = Color(0xFF2E358F)
private val onSecondaryContainerDark = Color(0xFFCFD1FF)
private val tertiaryDark = Color(0xFFF6ADFF)
private val onTertiaryDark = Color(0xFF560069)
private val tertiaryContainerDark = Color(0xFF6F0087)
private val onTertiaryContainerDark = Color(0xFFFAC3FF)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF12131D)
private val onBackgroundDark = Color(0xFFE3E1F0)
private val surfaceDark = Color(0xFF12131D)
private val onSurfaceDark = Color(0xFFE3E1F0)
private val surfaceVariantDark = Color(0xFF454557)
private val onSurfaceVariantDark = Color(0xFFC5C4DA)
private val outlineDark = Color(0xFF8F8FA3)
private val outlineVariantDark = Color(0xFF454557)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFE3E1F0)
private val inverseOnSurfaceDark = Color(0xFF2F2F3B)
private val inversePrimaryDark = Color(0xFF323DFF)
private val surfaceDimDark = Color(0xFF12131D)
private val surfaceBrightDark = Color(0xFF383844)
private val surfaceContainerLowestDark = Color(0xFF0D0D17)
private val surfaceContainerLowDark = Color(0xFF1A1B25)
private val surfaceContainerDark = Color(0xFF1E1F29)
private val surfaceContainerHighDark = Color(0xFF292934)
private val surfaceContainerHighestDark = Color(0xFF34343F)

private val primaryDarkMediumContrast = Color(0xFFC3C6FF)
private val onPrimaryDarkMediumContrast = Color(0xFF00015D)
private val primaryContainerDarkMediumContrast = Color(0xFF7B85FF)
private val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
private val secondaryDarkMediumContrast = Color(0xFFC3C6FF)
private val onSecondaryDarkMediumContrast = Color(0xFF00015D)
private val secondaryContainerDarkMediumContrast = Color(0xFF8188E7)
private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
private val tertiaryDarkMediumContrast = Color(0xFFF7B3FF)
private val onTertiaryDarkMediumContrast = Color(0xFF2C0037)
private val tertiaryContainerDarkMediumContrast = Color(0xFFD063E7)
private val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
private val errorDarkMediumContrast = Color(0xFFFFBAB1)
private val onErrorDarkMediumContrast = Color(0xFF370001)
private val errorContainerDarkMediumContrast = Color(0xFFFF5449)
private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
private val backgroundDarkMediumContrast = Color(0xFF12131D)
private val onBackgroundDarkMediumContrast = Color(0xFFE3E1F0)
private val surfaceDarkMediumContrast = Color(0xFF12131D)
private val onSurfaceDarkMediumContrast = Color(0xFFFDF9FF)
private val surfaceVariantDarkMediumContrast = Color(0xFF454557)
private val onSurfaceVariantDarkMediumContrast = Color(0xFFCAC9DE)
private val outlineDarkMediumContrast = Color(0xFFA1A1B6)
private val outlineVariantDarkMediumContrast = Color(0xFF818195)
private val scrimDarkMediumContrast = Color(0xFF000000)
private val inverseSurfaceDarkMediumContrast = Color(0xFFE3E1F0)
private val inverseOnSurfaceDarkMediumContrast = Color(0xFF292934)
private val inversePrimaryDarkMediumContrast = Color(0xFF020BEE)
private val surfaceDimDarkMediumContrast = Color(0xFF12131D)
private val surfaceBrightDarkMediumContrast = Color(0xFF383844)
private val surfaceContainerLowestDarkMediumContrast = Color(0xFF0D0D17)
private val surfaceContainerLowDarkMediumContrast = Color(0xFF1A1B25)
private val surfaceContainerDarkMediumContrast = Color(0xFF1E1F29)
private val surfaceContainerHighDarkMediumContrast = Color(0xFF292934)
private val surfaceContainerHighestDarkMediumContrast = Color(0xFF34343F)

private val primaryDarkHighContrast = Color(0xFFFDF9FF)
private val onPrimaryDarkHighContrast = Color(0xFF000000)
private val primaryContainerDarkHighContrast = Color(0xFFC3C6FF)
private val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
private val secondaryDarkHighContrast = Color(0xFFFDF9FF)
private val onSecondaryDarkHighContrast = Color(0xFF000000)
private val secondaryContainerDarkHighContrast = Color(0xFFC3C6FF)
private val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
private val tertiaryDarkHighContrast = Color(0xFFFFF9FA)
private val onTertiaryDarkHighContrast = Color(0xFF000000)
private val tertiaryContainerDarkHighContrast = Color(0xFFF7B3FF)
private val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
private val errorDarkHighContrast = Color(0xFFFFF9F9)
private val onErrorDarkHighContrast = Color(0xFF000000)
private val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
private val onErrorContainerDarkHighContrast = Color(0xFF000000)
private val backgroundDarkHighContrast = Color(0xFF12131D)
private val onBackgroundDarkHighContrast = Color(0xFFE3E1F0)
private val surfaceDarkHighContrast = Color(0xFF12131D)
private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkHighContrast = Color(0xFF454557)
private val onSurfaceVariantDarkHighContrast = Color(0xFFFDF9FF)
private val outlineDarkHighContrast = Color(0xFFCAC9DE)
private val outlineVariantDarkHighContrast = Color(0xFFCAC9DE)
private val scrimDarkHighContrast = Color(0xFF000000)
private val inverseSurfaceDarkHighContrast = Color(0xFFE3E1F0)
private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
private val inversePrimaryDarkHighContrast = Color(0xFF000497)
private val surfaceDimDarkHighContrast = Color(0xFF12131D)
private val surfaceBrightDarkHighContrast = Color(0xFF383844)
private val surfaceContainerLowestDarkHighContrast = Color(0xFF0D0D17)
private val surfaceContainerLowDarkHighContrast = Color(0xFF1A1B25)
private val surfaceContainerDarkHighContrast = Color(0xFF1E1F29)
private val surfaceContainerHighDarkHighContrast = Color(0xFF292934)
private val surfaceContainerHighestDarkHighContrast = Color(0xFF34343F)

private val sereneLightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

private val sereneDarkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)

private val sereneMediumContrastLightColorScheme = lightColorScheme(
    primary = primaryLightMediumContrast,
    onPrimary = onPrimaryLightMediumContrast,
    primaryContainer = primaryContainerLightMediumContrast,
    onPrimaryContainer = onPrimaryContainerLightMediumContrast,
    secondary = secondaryLightMediumContrast,
    onSecondary = onSecondaryLightMediumContrast,
    secondaryContainer = secondaryContainerLightMediumContrast,
    onSecondaryContainer = onSecondaryContainerLightMediumContrast,
    tertiary = tertiaryLightMediumContrast,
    onTertiary = onTertiaryLightMediumContrast,
    tertiaryContainer = tertiaryContainerLightMediumContrast,
    onTertiaryContainer = onTertiaryContainerLightMediumContrast,
    error = errorLightMediumContrast,
    onError = onErrorLightMediumContrast,
    errorContainer = errorContainerLightMediumContrast,
    onErrorContainer = onErrorContainerLightMediumContrast,
    background = backgroundLightMediumContrast,
    onBackground = onBackgroundLightMediumContrast,
    surface = surfaceLightMediumContrast,
    onSurface = onSurfaceLightMediumContrast,
    surfaceVariant = surfaceVariantLightMediumContrast,
    onSurfaceVariant = onSurfaceVariantLightMediumContrast,
    outline = outlineLightMediumContrast,
    outlineVariant = outlineVariantLightMediumContrast,
    scrim = scrimLightMediumContrast,
    inverseSurface = inverseSurfaceLightMediumContrast,
    inverseOnSurface = inverseOnSurfaceLightMediumContrast,
    inversePrimary = inversePrimaryLightMediumContrast,
    surfaceDim = surfaceDimLightMediumContrast,
    surfaceBright = surfaceBrightLightMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = surfaceContainerLowLightMediumContrast,
    surfaceContainer = surfaceContainerLightMediumContrast,
    surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
)

private val sereneHighContrastLightColorScheme = lightColorScheme(
    primary = primaryLightHighContrast,
    onPrimary = onPrimaryLightHighContrast,
    primaryContainer = primaryContainerLightHighContrast,
    onPrimaryContainer = onPrimaryContainerLightHighContrast,
    secondary = secondaryLightHighContrast,
    onSecondary = onSecondaryLightHighContrast,
    secondaryContainer = secondaryContainerLightHighContrast,
    onSecondaryContainer = onSecondaryContainerLightHighContrast,
    tertiary = tertiaryLightHighContrast,
    onTertiary = onTertiaryLightHighContrast,
    tertiaryContainer = tertiaryContainerLightHighContrast,
    onTertiaryContainer = onTertiaryContainerLightHighContrast,
    error = errorLightHighContrast,
    onError = onErrorLightHighContrast,
    errorContainer = errorContainerLightHighContrast,
    onErrorContainer = onErrorContainerLightHighContrast,
    background = backgroundLightHighContrast,
    onBackground = onBackgroundLightHighContrast,
    surface = surfaceLightHighContrast,
    onSurface = onSurfaceLightHighContrast,
    surfaceVariant = surfaceVariantLightHighContrast,
    onSurfaceVariant = onSurfaceVariantLightHighContrast,
    outline = outlineLightHighContrast,
    outlineVariant = outlineVariantLightHighContrast,
    scrim = scrimLightHighContrast,
    inverseSurface = inverseSurfaceLightHighContrast,
    inverseOnSurface = inverseOnSurfaceLightHighContrast,
    inversePrimary = inversePrimaryLightHighContrast,
    surfaceDim = surfaceDimLightHighContrast,
    surfaceBright = surfaceBrightLightHighContrast,
    surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = surfaceContainerLowLightHighContrast,
    surfaceContainer = surfaceContainerLightHighContrast,
    surfaceContainerHigh = surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
)

private val sereneMediumContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkMediumContrast,
    onPrimary = onPrimaryDarkMediumContrast,
    primaryContainer = primaryContainerDarkMediumContrast,
    onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
    secondary = secondaryDarkMediumContrast,
    onSecondary = onSecondaryDarkMediumContrast,
    secondaryContainer = secondaryContainerDarkMediumContrast,
    onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
    tertiary = tertiaryDarkMediumContrast,
    onTertiary = onTertiaryDarkMediumContrast,
    tertiaryContainer = tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
    error = errorDarkMediumContrast,
    onError = onErrorDarkMediumContrast,
    errorContainer = errorContainerDarkMediumContrast,
    onErrorContainer = onErrorContainerDarkMediumContrast,
    background = backgroundDarkMediumContrast,
    onBackground = onBackgroundDarkMediumContrast,
    surface = surfaceDarkMediumContrast,
    onSurface = onSurfaceDarkMediumContrast,
    surfaceVariant = surfaceVariantDarkMediumContrast,
    onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
    outline = outlineDarkMediumContrast,
    outlineVariant = outlineVariantDarkMediumContrast,
    scrim = scrimDarkMediumContrast,
    inverseSurface = inverseSurfaceDarkMediumContrast,
    inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
    inversePrimary = inversePrimaryDarkMediumContrast,
    surfaceDim = surfaceDimDarkMediumContrast,
    surfaceBright = surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
    surfaceContainer = surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
)

private val sereneHighContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkHighContrast,
    onPrimary = onPrimaryDarkHighContrast,
    primaryContainer = primaryContainerDarkHighContrast,
    onPrimaryContainer = onPrimaryContainerDarkHighContrast,
    secondary = secondaryDarkHighContrast,
    onSecondary = onSecondaryDarkHighContrast,
    secondaryContainer = secondaryContainerDarkHighContrast,
    onSecondaryContainer = onSecondaryContainerDarkHighContrast,
    tertiary = tertiaryDarkHighContrast,
    onTertiary = onTertiaryDarkHighContrast,
    tertiaryContainer = tertiaryContainerDarkHighContrast,
    onTertiaryContainer = onTertiaryContainerDarkHighContrast,
    error = errorDarkHighContrast,
    onError = onErrorDarkHighContrast,
    errorContainer = errorContainerDarkHighContrast,
    onErrorContainer = onErrorContainerDarkHighContrast,
    background = backgroundDarkHighContrast,
    onBackground = onBackgroundDarkHighContrast,
    surface = surfaceDarkHighContrast,
    onSurface = onSurfaceDarkHighContrast,
    surfaceVariant = surfaceVariantDarkHighContrast,
    onSurfaceVariant = onSurfaceVariantDarkHighContrast,
    outline = outlineDarkHighContrast,
    outlineVariant = outlineVariantDarkHighContrast,
    scrim = scrimDarkHighContrast,
    inverseSurface = inverseSurfaceDarkHighContrast,
    inverseOnSurface = inverseOnSurfaceDarkHighContrast,
    inversePrimary = inversePrimaryDarkHighContrast,
    surfaceDim = surfaceDimDarkHighContrast,
    surfaceBright = surfaceBrightDarkHighContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = surfaceContainerLowDarkHighContrast,
    surfaceContainer = surfaceContainerDarkHighContrast,
    surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
)

val sereneColorSchemes = ColorSchemes(
    light = sereneLightScheme,
    dark = sereneDarkScheme,
    mediumContrastLight = sereneMediumContrastLightColorScheme,
    mediumContrastDark = sereneMediumContrastDarkColorScheme,
    highContrastLight = sereneHighContrastLightColorScheme,
    highContrastDark = sereneHighContrastDarkColorScheme,
    nameRes = R.string.label_color_scheme_serene,
)
