package com.looker.kenko.ui.theme.colorSchemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Lime & Purple

private val primaryLight = Color(0xFF63611E)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFF7F3A1)
private val onPrimaryContainerLight = Color(0xFF545210)
private val secondaryLight = Color(0xFF62603E)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFF5F1C6)
private val onSecondaryContainerLight = Color(0xFF525131)
private val tertiaryLight = Color(0xFF70576B)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFE5C4DC)
private val onTertiaryContainerLight = Color(0xFF4A3447)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF410002)
private val backgroundLight = Color(0xFFFDF9F0)
private val onBackgroundLight = Color(0xFF1C1C16)
private val surfaceLight = Color(0xFFFDF9F0)
private val onSurfaceLight = Color(0xFF1C1C16)
private val surfaceVariantLight = Color(0xFFE7E3D0)
private val onSurfaceVariantLight = Color(0xFF49473A)
private val outlineLight = Color(0xFF7A7768)
private val outlineVariantLight = Color(0xFFCAC7B5)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF31302A)
private val inverseOnSurfaceLight = Color(0xFFF4F0E7)
private val inversePrimaryLight = Color(0xFFCDCA7C)
private val surfaceDimLight = Color(0xFFDDDAD1)
private val surfaceBrightLight = Color(0xFFFDF9F0)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFF7F3EA)
private val surfaceContainerLight = Color(0xFFF2EEE4)
private val surfaceContainerHighLight = Color(0xFFECE8DF)
private val surfaceContainerHighestLight = Color(0xFFE6E2D9)

private val primaryLightMediumContrast = Color(0xFF474502)
private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
private val primaryContainerLightMediumContrast = Color(0xFF7A7733)
private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryLightMediumContrast = Color(0xFF464425)
private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightMediumContrast = Color(0xFF787653)
private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryLightMediumContrast = Color(0xFF533B4F)
private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightMediumContrast = Color(0xFF876C82)
private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val errorLightMediumContrast = Color(0xFF8C0009)
private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
private val errorContainerLightMediumContrast = Color(0xFFDA342E)
private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
private val backgroundLightMediumContrast = Color(0xFFFDF9F0)
private val onBackgroundLightMediumContrast = Color(0xFF1C1C16)
private val surfaceLightMediumContrast = Color(0xFFFDF9F0)
private val onSurfaceLightMediumContrast = Color(0xFF1C1C16)
private val surfaceVariantLightMediumContrast = Color(0xFFE7E3D0)
private val onSurfaceVariantLightMediumContrast = Color(0xFF454336)
private val outlineLightMediumContrast = Color(0xFF616051)
private val outlineVariantLightMediumContrast = Color(0xFF7D7B6C)
private val scrimLightMediumContrast = Color(0xFF000000)
private val inverseSurfaceLightMediumContrast = Color(0xFF31302A)
private val inverseOnSurfaceLightMediumContrast = Color(0xFFF4F0E7)
private val inversePrimaryLightMediumContrast = Color(0xFFCDCA7C)
private val surfaceDimLightMediumContrast = Color(0xFFDDDAD1)
private val surfaceBrightLightMediumContrast = Color(0xFFFDF9F0)
private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightMediumContrast = Color(0xFFF7F3EA)
private val surfaceContainerLightMediumContrast = Color(0xFFF2EEE4)
private val surfaceContainerHighLightMediumContrast = Color(0xFFECE8DF)
private val surfaceContainerHighestLightMediumContrast = Color(0xFFE6E2D9)

private val primaryLightHighContrast = Color(0xFF252300)
private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
private val primaryContainerLightHighContrast = Color(0xFF474502)
private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val secondaryLightHighContrast = Color(0xFF242308)
private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightHighContrast = Color(0xFF464425)
private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryLightHighContrast = Color(0xFF301B2D)
private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightHighContrast = Color(0xFF533B4F)
private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val errorLightHighContrast = Color(0xFF4E0002)
private val onErrorLightHighContrast = Color(0xFFFFFFFF)
private val errorContainerLightHighContrast = Color(0xFF8C0009)
private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
private val backgroundLightHighContrast = Color(0xFFFDF9F0)
private val onBackgroundLightHighContrast = Color(0xFF1C1C16)
private val surfaceLightHighContrast = Color(0xFFFDF9F0)
private val onSurfaceLightHighContrast = Color(0xFF000000)
private val surfaceVariantLightHighContrast = Color(0xFFE7E3D0)
private val onSurfaceVariantLightHighContrast = Color(0xFF252419)
private val outlineLightHighContrast = Color(0xFF454336)
private val outlineVariantLightHighContrast = Color(0xFF454336)
private val scrimLightHighContrast = Color(0xFF000000)
private val inverseSurfaceLightHighContrast = Color(0xFF31302A)
private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
private val inversePrimaryLightHighContrast = Color(0xFFF4F09E)
private val surfaceDimLightHighContrast = Color(0xFFDDDAD1)
private val surfaceBrightLightHighContrast = Color(0xFFFDF9F0)
private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightHighContrast = Color(0xFFF7F3EA)
private val surfaceContainerLightHighContrast = Color(0xFFF2EEE4)
private val surfaceContainerHighLightHighContrast = Color(0xFFECE8DF)
private val surfaceContainerHighestLightHighContrast = Color(0xFFE6E2D9)

private val primaryDark = Color(0xFFFFFFFF)
private val onPrimaryDark = Color(0xFF333200)
private val primaryContainerDark = Color(0xFFDCD888)
private val onPrimaryContainerDark = Color(0xFF434100)
private val secondaryDark = Color(0xFFFFFFFF)
private val onSecondaryDark = Color(0xFF333214)
private val secondaryContainerDark = Color(0xFFDAD6AC)
private val onSecondaryContainerDark = Color(0xFF424122)
private val tertiaryDark = Color(0xFFFFE4F7)
private val onTertiaryDark = Color(0xFF3F293C)
private val tertiaryContainerDark = Color(0xFFD8B8D0)
private val onTertiaryContainerDark = Color(0xFF412C3E)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF14140E)
private val onBackgroundDark = Color(0xFFE6E2D9)
private val surfaceDark = Color(0xFF14140E)
private val onSurfaceDark = Color(0xFFE6E2D9)
private val surfaceVariantDark = Color(0xFF49473A)
private val onSurfaceVariantDark = Color(0xFFCAC7B5)
private val outlineDark = Color(0xFF949181)
private val outlineVariantDark = Color(0xFF49473A)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFE6E2D9)
private val inverseOnSurfaceDark = Color(0xFF31302A)
private val inversePrimaryDark = Color(0xFF63611E)
private val surfaceDimDark = Color(0xFF14140E)
private val surfaceBrightDark = Color(0xFF3A3933)
private val surfaceContainerLowestDark = Color(0xFF0F0E09)
private val surfaceContainerLowDark = Color(0xFF1C1C16)
private val surfaceContainerDark = Color(0xFF20201A)
private val surfaceContainerHighDark = Color(0xFF2B2A24)
private val surfaceContainerHighestDark = Color(0xFF36352F)

private val primaryDarkMediumContrast = Color(0xFFFFFFFF)
private val onPrimaryDarkMediumContrast = Color(0xFF333200)
private val primaryContainerDarkMediumContrast = Color(0xFFDCD888)
private val onPrimaryContainerDarkMediumContrast = Color(0xFF222100)
private val secondaryDarkMediumContrast = Color(0xFFFFFFFF)
private val onSecondaryDarkMediumContrast = Color(0xFF333214)
private val secondaryContainerDarkMediumContrast = Color(0xFFDAD6AC)
private val onSecondaryContainerDarkMediumContrast = Color(0xFF212005)
private val tertiaryDarkMediumContrast = Color(0xFFFFE4F7)
private val onTertiaryDarkMediumContrast = Color(0xFF3F293C)
private val tertiaryContainerDarkMediumContrast = Color(0xFFD8B8D0)
private val onTertiaryContainerDarkMediumContrast = Color(0xFF140413)
private val errorDarkMediumContrast = Color(0xFFFFBAB1)
private val onErrorDarkMediumContrast = Color(0xFF370001)
private val errorContainerDarkMediumContrast = Color(0xFFFF5449)
private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
private val backgroundDarkMediumContrast = Color(0xFF14140E)
private val onBackgroundDarkMediumContrast = Color(0xFFE6E2D9)
private val surfaceDarkMediumContrast = Color(0xFF14140E)
private val onSurfaceDarkMediumContrast = Color(0xFFFFFAF1)
private val surfaceVariantDarkMediumContrast = Color(0xFF49473A)
private val onSurfaceVariantDarkMediumContrast = Color(0xFFCECBB9)
private val outlineDarkMediumContrast = Color(0xFFA6A393)
private val outlineVariantDarkMediumContrast = Color(0xFF868474)
private val scrimDarkMediumContrast = Color(0xFF000000)
private val inverseSurfaceDarkMediumContrast = Color(0xFFE6E2D9)
private val inverseOnSurfaceDarkMediumContrast = Color(0xFF2B2A24)
private val inversePrimaryDarkMediumContrast = Color(0xFF4C4A07)
private val surfaceDimDarkMediumContrast = Color(0xFF14140E)
private val surfaceBrightDarkMediumContrast = Color(0xFF3A3933)
private val surfaceContainerLowestDarkMediumContrast = Color(0xFF0F0E09)
private val surfaceContainerLowDarkMediumContrast = Color(0xFF1C1C16)
private val surfaceContainerDarkMediumContrast = Color(0xFF20201A)
private val surfaceContainerHighDarkMediumContrast = Color(0xFF2B2A24)
private val surfaceContainerHighestDarkMediumContrast = Color(0xFF36352F)

private val primaryDarkHighContrast = Color(0xFFFFFFFF)
private val onPrimaryDarkHighContrast = Color(0xFF000000)
private val primaryContainerDarkHighContrast = Color(0xFFDCD888)
private val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
private val secondaryDarkHighContrast = Color(0xFFFFFFFF)
private val onSecondaryDarkHighContrast = Color(0xFF000000)
private val secondaryContainerDarkHighContrast = Color(0xFFDAD6AC)
private val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
private val tertiaryDarkHighContrast = Color(0xFFFFF9FA)
private val onTertiaryDarkHighContrast = Color(0xFF000000)
private val tertiaryContainerDarkHighContrast = Color(0xFFE2C1D9)
private val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
private val errorDarkHighContrast = Color(0xFFFFF9F9)
private val onErrorDarkHighContrast = Color(0xFF000000)
private val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
private val onErrorContainerDarkHighContrast = Color(0xFF000000)
private val backgroundDarkHighContrast = Color(0xFF14140E)
private val onBackgroundDarkHighContrast = Color(0xFFE6E2D9)
private val surfaceDarkHighContrast = Color(0xFF14140E)
private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkHighContrast = Color(0xFF49473A)
private val onSurfaceVariantDarkHighContrast = Color(0xFFFFFBEA)
private val outlineDarkHighContrast = Color(0xFFCECBB9)
private val outlineVariantDarkHighContrast = Color(0xFFCECBB9)
private val scrimDarkHighContrast = Color(0xFF000000)
private val inverseSurfaceDarkHighContrast = Color(0xFFE6E2D9)
private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
private val inversePrimaryDarkHighContrast = Color(0xFF2D2B00)
private val surfaceDimDarkHighContrast = Color(0xFF14140E)
private val surfaceBrightDarkHighContrast = Color(0xFF3A3933)
private val surfaceContainerLowestDarkHighContrast = Color(0xFF0F0E09)
private val surfaceContainerLowDarkHighContrast = Color(0xFF1C1C16)
private val surfaceContainerDarkHighContrast = Color(0xFF20201A)
private val surfaceContainerHighDarkHighContrast = Color(0xFF2B2A24)
private val surfaceContainerHighestDarkHighContrast = Color(0xFF36352F)

private val zestfulLightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

private val zestfulDarkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)

private val zestfulMediumContrastLightColorScheme = lightColorScheme(
    primary = primaryLightMediumContrast,
    onPrimary = onPrimaryLightMediumContrast,
    primaryContainer = primaryContainerLightMediumContrast,
    onPrimaryContainer = onPrimaryContainerLightMediumContrast,
    secondary = secondaryLightMediumContrast,
    onSecondary = onSecondaryLightMediumContrast,
    secondaryContainer = secondaryContainerLightMediumContrast,
    onSecondaryContainer = onSecondaryContainerLightMediumContrast,
    tertiary = tertiaryLightMediumContrast,
    onTertiary = onTertiaryLightMediumContrast,
    tertiaryContainer = tertiaryContainerLightMediumContrast,
    onTertiaryContainer = onTertiaryContainerLightMediumContrast,
    error = errorLightMediumContrast,
    onError = onErrorLightMediumContrast,
    errorContainer = errorContainerLightMediumContrast,
    onErrorContainer = onErrorContainerLightMediumContrast,
    background = backgroundLightMediumContrast,
    onBackground = onBackgroundLightMediumContrast,
    surface = surfaceLightMediumContrast,
    onSurface = onSurfaceLightMediumContrast,
    surfaceVariant = surfaceVariantLightMediumContrast,
    onSurfaceVariant = onSurfaceVariantLightMediumContrast,
    outline = outlineLightMediumContrast,
    outlineVariant = outlineVariantLightMediumContrast,
    scrim = scrimLightMediumContrast,
    inverseSurface = inverseSurfaceLightMediumContrast,
    inverseOnSurface = inverseOnSurfaceLightMediumContrast,
    inversePrimary = inversePrimaryLightMediumContrast,
    surfaceDim = surfaceDimLightMediumContrast,
    surfaceBright = surfaceBrightLightMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = surfaceContainerLowLightMediumContrast,
    surfaceContainer = surfaceContainerLightMediumContrast,
    surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
)

private val zestfulHighContrastLightColorScheme = lightColorScheme(
    primary = primaryLightHighContrast,
    onPrimary = onPrimaryLightHighContrast,
    primaryContainer = primaryContainerLightHighContrast,
    onPrimaryContainer = onPrimaryContainerLightHighContrast,
    secondary = secondaryLightHighContrast,
    onSecondary = onSecondaryLightHighContrast,
    secondaryContainer = secondaryContainerLightHighContrast,
    onSecondaryContainer = onSecondaryContainerLightHighContrast,
    tertiary = tertiaryLightHighContrast,
    onTertiary = onTertiaryLightHighContrast,
    tertiaryContainer = tertiaryContainerLightHighContrast,
    onTertiaryContainer = onTertiaryContainerLightHighContrast,
    error = errorLightHighContrast,
    onError = onErrorLightHighContrast,
    errorContainer = errorContainerLightHighContrast,
    onErrorContainer = onErrorContainerLightHighContrast,
    background = backgroundLightHighContrast,
    onBackground = onBackgroundLightHighContrast,
    surface = surfaceLightHighContrast,
    onSurface = onSurfaceLightHighContrast,
    surfaceVariant = surfaceVariantLightHighContrast,
    onSurfaceVariant = onSurfaceVariantLightHighContrast,
    outline = outlineLightHighContrast,
    outlineVariant = outlineVariantLightHighContrast,
    scrim = scrimLightHighContrast,
    inverseSurface = inverseSurfaceLightHighContrast,
    inverseOnSurface = inverseOnSurfaceLightHighContrast,
    inversePrimary = inversePrimaryLightHighContrast,
    surfaceDim = surfaceDimLightHighContrast,
    surfaceBright = surfaceBrightLightHighContrast,
    surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = surfaceContainerLowLightHighContrast,
    surfaceContainer = surfaceContainerLightHighContrast,
    surfaceContainerHigh = surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
)

private val zestfulMediumContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkMediumContrast,
    onPrimary = onPrimaryDarkMediumContrast,
    primaryContainer = primaryContainerDarkMediumContrast,
    onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
    secondary = secondaryDarkMediumContrast,
    onSecondary = onSecondaryDarkMediumContrast,
    secondaryContainer = secondaryContainerDarkMediumContrast,
    onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
    tertiary = tertiaryDarkMediumContrast,
    onTertiary = onTertiaryDarkMediumContrast,
    tertiaryContainer = tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
    error = errorDarkMediumContrast,
    onError = onErrorDarkMediumContrast,
    errorContainer = errorContainerDarkMediumContrast,
    onErrorContainer = onErrorContainerDarkMediumContrast,
    background = backgroundDarkMediumContrast,
    onBackground = onBackgroundDarkMediumContrast,
    surface = surfaceDarkMediumContrast,
    onSurface = onSurfaceDarkMediumContrast,
    surfaceVariant = surfaceVariantDarkMediumContrast,
    onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
    outline = outlineDarkMediumContrast,
    outlineVariant = outlineVariantDarkMediumContrast,
    scrim = scrimDarkMediumContrast,
    inverseSurface = inverseSurfaceDarkMediumContrast,
    inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
    inversePrimary = inversePrimaryDarkMediumContrast,
    surfaceDim = surfaceDimDarkMediumContrast,
    surfaceBright = surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
    surfaceContainer = surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
)

private val zestfulHighContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkHighContrast,
    onPrimary = onPrimaryDarkHighContrast,
    primaryContainer = primaryContainerDarkHighContrast,
    onPrimaryContainer = onPrimaryContainerDarkHighContrast,
    secondary = secondaryDarkHighContrast,
    onSecondary = onSecondaryDarkHighContrast,
    secondaryContainer = secondaryContainerDarkHighContrast,
    onSecondaryContainer = onSecondaryContainerDarkHighContrast,
    tertiary = tertiaryDarkHighContrast,
    onTertiary = onTertiaryDarkHighContrast,
    tertiaryContainer = tertiaryContainerDarkHighContrast,
    onTertiaryContainer = onTertiaryContainerDarkHighContrast,
    error = errorDarkHighContrast,
    onError = onErrorDarkHighContrast,
    errorContainer = errorContainerDarkHighContrast,
    onErrorContainer = onErrorContainerDarkHighContrast,
    background = backgroundDarkHighContrast,
    onBackground = onBackgroundDarkHighContrast,
    surface = surfaceDarkHighContrast,
    onSurface = onSurfaceDarkHighContrast,
    surfaceVariant = surfaceVariantDarkHighContrast,
    onSurfaceVariant = onSurfaceVariantDarkHighContrast,
    outline = outlineDarkHighContrast,
    outlineVariant = outlineVariantDarkHighContrast,
    scrim = scrimDarkHighContrast,
    inverseSurface = inverseSurfaceDarkHighContrast,
    inverseOnSurface = inverseOnSurfaceDarkHighContrast,
    inversePrimary = inversePrimaryDarkHighContrast,
    surfaceDim = surfaceDimDarkHighContrast,
    surfaceBright = surfaceBrightDarkHighContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = surfaceContainerLowDarkHighContrast,
    surfaceContainer = surfaceContainerDarkHighContrast,
    surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
)

val zestfulColorSchemes = ColorSchemes(
    light = zestfulLightScheme,
    dark = zestfulDarkScheme,
    mediumContrastLight = zestfulMediumContrastLightColorScheme,
    mediumContrastDark = zestfulMediumContrastDarkColorScheme,
    highContrastLight = zestfulHighContrastLightColorScheme,
    highContrastDark = zestfulHighContrastDarkColorScheme,
)
